<html>
<head>
<title></title>
</head>
<body topmargin="0" leftmargin="0">
<table width=100%>
<tr>	
    <td width="100%" colspan="2" height="1">
    <table cellspacing="1" style="border-collapse: collapse; border-top: 1px solid #FF9933" width="100%" id="AutoNumber3">
      <tr>
        <td width="50%"><font size="2" face="Arial">©2004 Karnataka Silk Industries Corporation</font></td>
        <td width="50%">
        <p align="right"><font face="Arial"><font size="2">Maintained by </font> <a href="http://www.e-syma.com">
        <font size="2">E-Syma Services</font></a></font></td>
      </tr>
    </table>
    </td>
</tr>
</table>
</body>
</html>
