<html>
<head>
<title></title>
</head>
<body topmargin="0" leftmargin="0">
<table border="0" cellspacing="1" style="border-collapse: collapse" bordercolor="#111111" width="100%" id="AutoNumber1">
  <tr>
    <td width="50%" style="border-bottom: 1px solid #FF9933" valign="baseline" height="66">
        <p align="right">
        <img border="0" src="images/ksiclogo.gif" align="left" width="320" height="65"><font size="4" color="#FF0000">&nbsp;&nbsp;
        </font></td>
    <td style="border-bottom: 1px solid #FF9933" align="right" height="66" >
        <table border="0" cellspacing="0" style="border-collapse: collapse" bordercolor="#111111" id="AutoNumber4" cellpadding="0" height="20">
          <tr>
		   <tr>
                    <td width="60" height="13" align="center" style="border: 1 solid #EEBC44" bgcolor="#FFFFE1"><font color="#FFEFD6" face="Arial Black" size="1"><a href="aboutus.htm"><span style="font-size: 7pt"><b>about us</b></span></a></font></td>
                    <td width="88" height="13" align="center" style="border-right: 1 solid #EEBC44; border-top: 1 solid #EEBC44; border-bottom: 1 solid #EEBC44" bgcolor="#FFFFE1"><font color="#FFEFD6" face="Arial Black" size="1"><a href="ksicshowrooms.htm"><span style="font-size: 7pt"><b>ksic showrooms</b></span></a></font></td>
                    <td width="62" height="13" align="center" style="border-right: 1 solid #EEBC44; border-top: 1 solid #EEBC44; border-bottom: 1 solid #EEBC44" bgcolor="#FFFFE1"><font color="#FFEFD6" face="Arial Black" size="1"><b><a href="palludesigns.htm"><span style="font-size: 7pt">pallu design</span></a></b></font></td>
                  </tr>
                  <tr>
                    <td width="60" height="13" align="center" style="border-left: 1 solid #EEBC44; border-right: 1 solid #EEBC44; border-bottom: 1 solid #EEBC44" bgcolor="#FFFFE1"><font color="#FFEFD6" face="Arial Black" size="1"><a href="factories.htm"><span style="font-size: 7pt"><b>factories</b></span></a></font></td>
                    <td width="88" height="13" align="center" style="border-right: 1 solid #EEBC44; border-bottom: 1 solid #EEBC44" bgcolor="#FFFFE1"><font color="#FFEFD6" face="Arial Black" size="1"><a href="generalsareespecification.asp"><span style="font-size: 7pt"><b>saree spec. &amp; buy</b></span></a></font></td>
                    <td width="62" height="13" align="center" style="border-right: 1 solid #EEBC44; border-bottom: 1 solid #EEBC44" bgcolor="#FFFFE1"><font color="#FFEFD6" face="Arial Black" size="1"><b><a href="tendercell.htm"><span style="font-size: 7pt">tender
                      cell</span></a></b></font></td>
                  </tr>
                  <tr>
                    <td width="60" height="13" align="center" style="border-left: 1 solid #EEBC44; border-right: 1 solid #EEBC44; border-bottom: 1 solid #EEBC44" bgcolor="#FFFFE1"><font color="#FFEFD6" face="Arial Black" size="1"><a href="products.htm"><span style="font-size: 7pt"><b>products</b></span></a></font></td>
                    <td width="88" height="13" align="center" style="border-right: 1 solid #EEBC44; border-bottom: 1 solid #EEBC44" bgcolor="#FFFFE1"><font color="#FFEFD6" face="Arial Black" size="1"><a href="tipsilkcare.htm"><span style="font-size: 7pt"><b>care your silk</b></span></a></font></td>
                    <td width="62" height="13" align="center" style="border-right: 1 solid #EEBC44; border-bottom: 1 solid #EEBC44" bgcolor="#FFFFE1"><font color="#FFEFD6" face="Arial Black" size="1"><b><a href="index.htm"><span style="font-size: 7pt">home</span></a></b></font></td>
                  </tr>
            
          </tr>
        </table>
</tr>
</table>

</body>
</html>