<!-- This page is to gather Customer information -->
	<p class="Normal">
	Your order is ready for submission. 
	Please provide the following information and click the "Buy Now" button.<br><br><br>
<table align="center" border="0" ID="Table1">
		<tr bgcolor="#c0c0c0" class="Normal">
			<th colspan="4" align="center">
				<p align="center">Customer Information
			</th> 
		</tr>
		<tr class="Normal">
			<td align="right">First Name:</td>
			<td colspan="3"><input type="Text" name="billing_cust_name" size="35" maxlength="30" ID="billing_cust_name"></td>
		</tr>
		<tr class="Normal">
			<td align="right">Last Name:</td>
			<td colspan="3"><input type="Text" name="billing_last_name" size="35" maxlength="30" ID="billing_last_name"></td>
		</tr>

		<tr class="Normal">
			<td align="right">Address:</td>
			<td colspan="3"><input type="Text" name="billing_cust_address" size="35" maxlength="100" ID="billing_cust_address"></td>
		</tr>
		<tr class="Normal">
			<td align="right">City:</td>
			<td colspan="3"><input type="Text" name="billing_cust_city" size="35" maxlength="30" ID="billing_cust_city"></td>
		</tr>
		<tr class="Normal">
			<td align="right">State:</td>
			<td><input type="Text" name="billing_cust_state" size="14" maxlength="15" ID="billing_cust_state"></td>
			<td>ZIP:</td>
			<td><font face="Verdana,Arial" size="-1"><input type="Text" name="billing_cust_zip" size="11" maxlength="7" ID="billing_cust_zip"></td>
		</tr>
			<tr class="Normal">
			<td align="right">Country<br>
			<font size="1">(If necessary or leave blank)</font></td>
			<td colspan="3">
<!-- ------------------------ -->
<select name="billing_cust_country" size="1">
<option value="">--Select--</option>
<option value="AF">Afghanistan</option>
<option value="AL">Albania</option>
<option value="DZ">Algeria</option>
<option value="AS">American Samoa</option>
<option value="AD">Andorra</option>
<option value="AO">Angola</option>
<option value="AI">Anguilla</option>
<option value="AN">Antarctica</option>
<option value="AB">Antigua And Barbuda</option>
<option value="AR">Argentina</option>
<option value="AM">Armenia</option>
<option value="AW">Aruba</option>
<option value="AU">Australia</option>
<option value="AT">Austria</option>
<option value="AZ">Azerbaijan</option>
<option value="BS">Bahamas</option>
<option value="BH">Bahrain</option>
<option value="BD">Bangladesh</option>
<option value="BB">Barbados</option>
<option value="BL">Belarus</option>
<option value="BE">Belgium</option>
<option value="BZ">Belize</option>
<option value="BJ">Benin</option>
<option value="BM">Bermuda</option>
<option value="BT">Bhutan</option>
<option value="BO">Bolivia</option>
<option value="BW">Botswana</option>
<option value="BU">Bouvet Island</option>
<option value="BR">Brazil</option>
<option value="BN">Brunei</option>
<option value="BG">Bulgaria</option>
<option value="BF">Burkina Faso</option>
<option value="BI">Burundi</option>
<option value="KH">Cambodia</option>
<option value="CM">Cameroon</option>
<option value="CA">Canada</option>
<option value="CV">Cape Verde</option>
<option value="KY">Cayman Islands</option>
<option value="TD">Chad</option>
<option value="CL">Chile</option>
<option value="CN">China</option>
<option value="CI">Christmas Island</option>
<option value="CO">Colombia</option>
<option value="KM">Comoros</option>
<option value="CG">Congo</option>
<option value="CK">Cook Islands</option>
<option value="CR">Costa Rica</option>
<option value="CT">Croatia (Hrvatska)</option>
<option value="CU">Cuba</option>
<option value="CY">Cyprus</option>
<option value="CZ">Czech Republic</option>
<option value="DK">Denmark</option>
<option value="DJ">Djibouti</option>
<option value="DC">Dominica</option>
<option value="DO">Dominican Republic</option>
<option value="EM">East Timor</option>
<option value="EC">Ecuador</option>
<option value="EG">Egypt</option>
<option value="EL">ElSalvador</option>
<option value="GQ">Equatorial Guinea</option>
<option value="ER">Eritrea</option>
<option value="EN">Estonia</option>
<option value="ET">Ethiopia</option>
<option value="FD">Faroe Islands</option>
<option value="FJ">Fiji Islands</option>
<option value="FI">Finland</option>
<option value="FR">France</option>
<option value="FU">French Guiana</option>
<option value="PF">French Polynesia</option>
<option value="GA">Gabon</option>
<option value="GM">Gambia</option>
<option value="GG">Georgia</option>
<option value="DE">Germany</option>
<option value="GH">Ghana</option>
<option value="GI">Gibraltar</option>
<option value="GR">Greece</option>
<option value="GL">Greenland</option>
<option value="GD">Grenada</option>
<option value="GP">Guadeloupe</option>
<option value="GU">Guam</option>
<option value="GT">Guatemala</option>
<option value="GN">Guinea</option>
<option value="GB">Guinea-Bissau</option>
<option value="GY">Guyana</option>
<option value="HV">Haitiv</option>
<option value="HN">Honduras</option>
<option value="HK">Hong Kong</option>
<option value="HU">Hungary</option>
<option value="IS">Iceland</option>
<option value="IN">India</option>
<option value="ID">Indonesia</option>
<option value="IR">Iran</option>
<option value="IQ">Iraq</option>
<option value="IE">Ireland</option>
<option value="IL">Israel</option>
<option value="IT">Italy</option>
<option value="JM">Jamaica</option>
<option value="JP">Japan</option>
<option value="JO">Jordan</option>
<option value="KZ">Kazakhstan</option>
<option value="KE">Kenya</option>
<option value="KI">Kiribati</option>
<option value="KW">Kuwait</option>
<option value="KG">Kyrgyzstan</option>
<option value="LA">Laos</option>
<option value="LV">Latvia</option>
<option value="LB">Lebanon</option>
<option value="LS">Lesotho</option>
<option value="LR">Liberia</option>
<option value="LY">Libya</option>
<option value="LT">Liechtenstein</option>
<option value="LN">Lithuania</option>
<option value="LU">Luxembourg</option>
<option value="MC">Macao</option>
<option value="MD">Macedonia</option>
<option value="MG">Madagascar</option>
<option value="MW">Malawi</option>
<option value="MY">Malaysia</option>
<option value="MV">Maldives</option>
<option value="ML">Mali</option>
<option value="MT">Malta</option>
<option value="MH">Marshall Islands</option>
<option value="MR">Mauritania</option>
<option value="MU">Mauritius</option>
<option value="ME">Mayotte</option>
<option value="MX">Mexico</option>
<option value="MI">Micronesia</option>
<option value="MO">Moldova</option>
<option value="MK">Monaco</option>
<option value="MN">Mongolia</option>
<option value="MS">Montserrat</option>
<option value="MA">Morocco</option>
<option value="MZ">Mozambique</option>
<option value="MM">Myanmar</option>
<option value="NA">Namibia</option>
<option value="NR">Nauru</option>
<option value="NP">Nepal</option>
<option value="NL">Netherlands</option>
<option value="HO">Netherlands Antilles</option>
<option value="NC">New Caledonia</option>
<option value="NZ">New Zealand</option>
<option value="NI">Nicaragua</option>
<option value="NE">Niger</option>
<option value="NG">Nigeria</option>
<option value="NU">Niue</option>
<option value="NF">Norfolk Island</option>
<option value="NK">North Korea</option>
<option value="NO">Norway</option>
<option value="OM">Oman</option>
<option value="PK">Pakistan</option>
<option value="PU">Palau</option>
<option value="PA">Panama</option>
<option value="PG">Papua new Guinea</option>
<option value="PY">Paraguay</option>
<option value="PE">Peru</option>
<option value="PH">Philippines</option>
<option value="PI">Pitcairn Island</option>
<option value="PL">Poland</option>
<option value="PT">Portugal</option>
<option value="PR">Puerto Rico</option>
<option value="QA">Qatar</option>
<option value="RE">Reunion</option>
<option value="RO">Romania</option>
<option value="RS">Russia</option>
<option value="RW">Rwanda</option>
<option value="SH">Saint Helena</option>
<option value="SL">Saint Lucia</option>
<option value="WS">Samoa</option>
<option value="SM">San Marino</option>
<option value="SA">Saudi Arabia</option>
<option value="SN">Senegal</option>
<option value="SC">Seychelles</option>
<option value="LE">Sierra Leone</option>
<option value="SG">Singapore</option>
<option value="SV">Slovakia</option>
<option value="SI">Slovenia</option>
<option value="SB">Solomon Islands</option>
<option value="SO">Somalia</option>
<option value="ZA">South Africa</option>
<option value="SK">South Korea</option>
<option value="ES">Spain</option>
<option value="LK">Sri Lanka</option>
<option value="SD">Sudan</option>
<option value="SR">Suriname</option>
<option value="SZ">Swaziland</option>
<option value="SE">Sweden</option>
<option value="CH">Switzerland</option>
<option value="SY">Syria</option>
<option value="TW">Taiwan</option>
<option value="TJ">Tajikistan</option>
<option value="TA">Tanzania</option>
<option value="TH">Thailand</option>
<option value="TG">Togo</option>
<option value="TL">Tokelau</option>
<option value="TO">Tonga</option>
<option value="TT">Trinidad And Tobago</option>
<option value="TN">Tunisia</option>
<option value="TR">Turkey</option>
<option value="TK">Turkmenistan</option>
<option value="TV">Tuvalu</option>
<option value="UG">Uganda</option>
<option value="UN">Ukraine</option>
<option value="AE">United Arab Emirates</option>
<option value="UK">United Kingdom</option>
<option value="US">United States</option>
<option value="UY">Uruguay</option>
<option value="UZ">Uzbekistan</option>
<option value="VU">Vanuatu</option>
<option value="VC">Vatican City</option>
<option value="VE">Venezuela</option>
<option value="VT">Vietnam</option>
<option value="WH">Western Sahara</option>
<option value="YE">Yemen</option>
<option value="YU">Yugoslavia</option>
<option value="ZM">Zambia</option>
<option value="ZW">Zimbabwe</option>
</select>

<!-- ------------------------ -->


</td>
		</tr>

		<tr class="Normal">
			<td align="right">Phone</td>
			<td colspan="3"><input type="Text" name="billing_cust_tel_No" size="35" maxlength="15" ID="billing_cust_tel_No"></td>
		</tr>
		<tr class="Normal">
			<td align="right">E-mail:</td>
			<td colspan="3"><input type="Text" name="billing_cust_email" size="35" maxlength="25" ID="billing_cust_email"></td>
		</tr>
</table>
