<!-- This page is to gather Customer information -->
	<p class="Normal">
	Your order is ready for submission. 
	Please provide the following information and click the "Submit Order" button.<br><br><br>
<table align="center" border="0" ID="Table1">
		<tr bgcolor="#c0c0c0" class="Normal">
			<th colspan="4" align="center">
				<p align="center">Customer Information
			</th> 
		</tr>
		<tr class="Normal">
			<td align="right">First Name:</td>
			<td colspan="3"><input type="Text" name="billing_cust_name" size="35" maxlength="30" ID="billing_cust_name"></td>
		</tr>
		<tr class="Normal">
			<td align="right">Last Name:</td>
			<td colspan="3"><input type="Text" name="billing_last_name" size="35" maxlength="30" ID="billing_last_name"></td>
		</tr>

		<tr class="Normal">
			<td align="right">Address:</td>
			<td colspan="3"><input type="Text" name="billing_cust_address" size="35" maxlength="100" ID="billing_cust_address"></td>
		</tr>
		<tr class="Normal">
			<td align="right">City:</td>
			<td colspan="3"><input type="Text" name="billing_cust_city" size="35" maxlength="30" ID="billing_cust_city"></td>
		</tr>
		<tr class="Normal">
			<td align="right">State:</td>
			<td><input type="Text" name="billing_cust_state" size="14" maxlength="15" ID="billing_cust_state"></td>
			<td>ZIP:</td>
			<td><font face="Verdana,Arial" size="-1"><input type="Text" name="billing_cust_zip" size="11" maxlength="7" ID="billing_cust_zip"></td>
		</tr>
			<tr class="Normal">
			<td align="right">Country<br>
			<font size="1">(If necessary or leave blank)</font></td>
			<td colspan="3"><input type="Text" name="billing_cust_country" size="35" maxlength="15" ID="billing_cust_country"></td>
		</tr>

		<tr class="Normal">
			<td align="right">Phone</td>
			<td colspan="3"><input type="Text" name="billing_cust_tel_No" size="35" maxlength="15" ID="billing_cust_tel_No"></td>
		</tr>
		<tr class="Normal">
			<td align="right">E-mail:</td>
			<td colspan="3"><input type="Text" name="billing_cust_email" size="35" maxlength="25" ID="billing_cust_email"></td>
		</tr>
</table>
